version: '3'

services:
  # Database container based on official postgres image.
  # Database username, name and password are only used if no database exists.
  db:
    image: j00sko/tomo_privat:db-latest
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=tomo
      - POSTGRES_DB=tomo
      - POSTGRES_PASSWORD=tomo_geslo

  # Tomo web service based on matijapretnar/projekt-tomo image.
  tomo:
    image: j00sko/tomo_privat:app-latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=web.settings.arnes
      - SECRET_KEY=type_your_secret_key
      - UWSGI_CHDIR=/home/tomo/projekt-tomo/web
      - UWSGI_MODULE=web.wsgi.arnes:application
      - UWSGI_MASTER=True
      - UWSGI_PIDFILE=/tmp/project-master.pid
      - UWSGI_VACUUM=True
      - UWSGI_MAX_REQUESTS=5000
      - UWSGI_UID=tomo
      - UWSGI_GID=tomo
      - UWSGI_HTTP=:8080
      - UWSGI_PLUGINS=python3
      - UWSGI_STATIC_MAP=/static=/home/tomo/projekt-tomo/web/static
    restart: always


volumes:
  dbdata: